import type { Metadata } from "next";
import { Poppins } from 'next/font/google'; // Import the font
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import PageTransition from "./components/PageTransition";
import NextTopLoader from "nextjs-toploader";
import "./globals.css";
import ScrollToggle from './components/ScrollToggle';

// Configure the font
const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '600', '700'], // 400=Regular, 600=SemiBold, 700=Bold
  variable: '--font-poppins',    // This creates a CSS variable
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} bg-black text-white`}
      >
<NextTopLoader 
  color="#18aed1" 
  initialPosition={0.08} 
  crawlSpeed={200} 
  height={3} 
  showSpinner={false} 
/>
        <Navbar />
        <PageTransition> 
          {children}
<ScrollToggle />
        </PageTransition>
       
        <Footer /> {/* Add it here */}
      </body>
    </html>
  );
}
